### ISSUE TITLE
How does this handle block-based updates?

### ISSUE THREAD

**Issue by luke-jr** [chriswoope/resign-android-image#10]
Graphene claims it uses block-based delta updates, which seems inherently incompatible with a modifiable system/root partition. Can this handle that somehow? Or it's just root access that can't actually modify the system much? What happens if the patching this does conflicts with blocks re-used in other ways later?

**Comment by chriswoope** [comment]
GrapheneOS OTAs don't actually use block-based delta updates and this script doesn't generate them.

If they started providing them exclusively, I would probably modify the script to always get the images from the factory image instead of the OTA.
