### ISSUE TITLE
Bluetooth doesn't work

### ISSUE THREAD

**Issue by genya1** [chriswoope/resign-android-image#14]
Hi, first of all, thank you so much for creating this. I really wanted Graphene with adb root.

I know you have stated that Android 13 has not been tested, but I have ran the script for Android 13 Pixel and everything works great except the Bluetooth.

Here is the adb logcat when I try to turn on bluetooth:
```
10-22 22:41:00.110  9918  9918 E SELinux : seapp_context_lookup:  No match for app with uid 1002, seinfo default, name com.android.bluetooth
10-22 22:41:00.110  9918  9918 E SELinux : selinux_android_setcontext:  Error setting context for app with uid 1002, seinfo default:privapp:targetSdkVersion=33:complete: Success
10-22 22:41:00.110  9918  9918 F zygote64: jni_internal.cc:825] JNI FatalError called: (com.android.bluetooth) frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:1766: selinux_android_setcontext(1002, 0, "default:privapp:targetSdkVersion=33:complete", "com.android.bluetooth") failed
```

From some researching and this [article](https://blog.rabit.pw/2017/seandroid-app-context/) I am assuming the bluetooth signing process didn't work correctly since the signatures don't match. I didn't have any errors during running the script.

**Comment by chriswoope** [comment]
Fixed
