### ISSUE TITLE
7 Series Support

### ISSUE THREAD

**Issue by xstefen** [chriswoope/resign-android-image#19]
Hi Chris, awesome work here. I build for my Pixel 7 Pro and I'd love to help you out on this where possible. Let's get in touch. me@xstefen.dev, can retrieve my gpg key via wkd, @xstefen on telegram, or let me know what works for you. Cheers

**Comment by xstefen** [comment]
ive expanded some support for non-grapheneos, still lots of work to go

**Comment by xstefen** [comment]
No, got side tracked and forgot to push before a format. I'll pick it up again

**Comment by robsmith11** [comment]
Is it working on your 7 pro?

**Comment by xstefen** [comment]
> Is it working on your 7 pro?

My sincerest apologies. Got rekt by a bad flash and lost my HWIDs. The G told me to play in traffic as I was 1 month out of warranty and by installing the beta I agree that my device can be irreversibly damaged due to the ease of error and the lack of proper tooling to recover.

I traded my junked cheetah in and for the first time in my life am using an iPhone...and somehow enjoying it.

Best of luck to you, cheers m8
